const { withAppBuildGradle } = require('@expo/config-plugins');

/**
 * Forces `debuggable true` on the Android release build type.
 *
 * Why: the reviewer/RUNBOOK path pushes model files into the app's private
 * storage via `adb shell run-as` — that only works if the installed APK is
 * debuggable. EAS's `preview` profile (no developmentClient) otherwise builds
 * a standard non-debuggable release variant, which silently breaks run-as on
 * any real device (`run-as: package not debuggable`), including production
 * phones where `adb root` is refused. `android/` is regenerated by Expo CNG
 * on every prebuild, so this must live in a config plugin, not a hand edit.
 */
module.exports = function withDebuggableRelease(config) {
  return withAppBuildGradle(config, (config) => {
    if (config.modResults.language === 'groovy') {
      config.modResults.contents = config.modResults.contents.replace(
        /release\s*\{/,
        'release {\n            debuggable true',
      );
    }
    return config;
  });
};
