/**
 * Overwhelm Manager microcopy — English verbatim from design/overwhelm/screen-spec.md §4.
 * Single source so the screen stays declarative. Tone rules (§4): warm, plain,
 * second person; never "server/upload/cloud/internet" except to reassure.
 *
 * Every translation follows the same tone rules — simple, warm, spoken register
 * (informal address where the language allows it: tú/du/tu/você), not formal register;
 * feature names stay in English (they're product names). Locale set = the eight
 * languages Llama 3.2 supports (see core/i18n/i18n.ts).
 */
import { localized } from '../core/i18n/i18n';

export const COPY = localized(
  {
    promptH1: "What's overwhelming you today?",
    subtext:
      "Type it out. I'll break it into small, doable steps — right here on your phone.",
    placeholder: 'e.g. "Plan my sister\'s birthday next weekend"',
    submitCta: 'Break it down',
    privacyFootnote: 'Runs fully on your device. Nothing is sent anywhere.',
    loadingTitle: 'Thinking this through on your device…',
    loadingOffline: 'Works in airplane mode. Your words never leave this phone.',
    // shown while the model is still loading/warming on first entry (integration §4.5)
    preparingTitle: 'Getting things ready, fully on your device.',
    taskChipLabel: 'You asked:',
    stopButton: 'Stop',
    allComplete: 'Nicely done. You handled it, one step at a time.',
    emptyResult:
      "I couldn't break that one down just now. Let's try again — or tweak the wording.",
    error: "Something hiccuped on this end. Your text is safe — let's try again.",
    retryButton: 'Try again',
    editButton: 'Edit',
    startOverButton: 'Start over',
    // "tap a step to go deeper" feature
    breakDownStepCta: 'Break this into smaller steps',
    breakingDownStep: 'Breaking this down on your device…',
    breakdownEmpty: "This one's already about as small as it gets.",
    breakdownError: "Couldn't split that one — try again.",
    // shown after the app restarts following a crash mid-generation (see RUNBOOK.md)
    recoveredDraftLabel: 'The app closed before finishing your last task:',
    recoveredDraftResume: 'Resume',
    recoveredDraftDismiss: 'Discard',
  },
  {
    es: {
      promptH1: '¿Qué te está abrumando hoy?',
      subtext: 'Escríbelo. Lo dividiré en pasos pequeños y manejables — aquí mismo, en tu teléfono.',
      placeholder: 'p. ej. «Organizar el cumpleaños de mi hermana el próximo fin de semana»',
      submitCta: 'Divídelo en pasos',
      privacyFootnote: 'Funciona por completo en tu teléfono. No se envía nada a ninguna parte.',
      loadingTitle: 'Pensándolo en tu teléfono…',
      loadingOffline: 'Funciona en modo avión. Tus palabras nunca salen de este teléfono.',
      preparingTitle: 'Preparando todo, directamente en tu teléfono.',
      taskChipLabel: 'Tu tarea:',
      stopButton: 'Detener',
      allComplete: 'Bien hecho. Lo resolviste, paso a paso.',
      emptyResult: 'No pude dividir esto ahora. Inténtalo de nuevo — o cambia un poco las palabras.',
      error: 'Algo falló por aquí. Tu texto está a salvo — intentémoslo de nuevo.',
      retryButton: 'Reintentar',
      editButton: 'Editar',
      startOverButton: 'Empezar de nuevo',
      breakDownStepCta: 'Dividir en pasos más pequeños',
      breakingDownStep: 'Dividiéndolo en tu teléfono…',
      breakdownEmpty: 'Este paso ya es lo más pequeño posible.',
      breakdownError: 'No pude dividirlo — inténtalo de nuevo.',
      recoveredDraftLabel: 'La app se cerró antes de terminar tu última tarea:',
      recoveredDraftResume: 'Continuar',
      recoveredDraftDismiss: 'Descartar',
    },
    fr: {
      promptH1: 'Qu’est-ce qui vous submerge aujourd’hui ?',
      subtext: 'Écrivez-le. Je vais le découper en petites étapes faisables — ici même, sur votre téléphone.',
      placeholder: 'ex. « Organiser l’anniversaire de ma sœur le week-end prochain »',
      submitCta: 'Découper en étapes',
      privacyFootnote: 'Fonctionne entièrement sur votre téléphone. Rien n’est envoyé nulle part.',
      loadingTitle: 'J’y réfléchis sur votre téléphone…',
      loadingOffline: 'Fonctionne en mode avion. Vos mots ne quittent jamais ce téléphone.',
      preparingTitle: 'Préparation en cours, entièrement sur votre téléphone.',
      taskChipLabel: 'Votre demande :',
      stopButton: 'Arrêter',
      allComplete: 'Bien joué. Vous y êtes arrivé, une étape à la fois.',
      emptyResult: 'Je n’ai pas réussi à le découper cette fois. Réessayez — ou reformulez un peu.',
      error: 'Un petit souci de notre côté. Votre texte est en sécurité — réessayons.',
      retryButton: 'Réessayer',
      editButton: 'Modifier',
      startOverButton: 'Recommencer',
      breakDownStepCta: 'Découper en étapes plus petites',
      breakingDownStep: 'Découpage en cours, sur votre téléphone…',
      breakdownEmpty: 'Cette étape est déjà aussi petite que possible.',
      breakdownError: 'Impossible de la découper — réessayez.',
      recoveredDraftLabel: 'L’appli s’est fermée avant de terminer votre dernière tâche :',
      recoveredDraftResume: 'Reprendre',
      recoveredDraftDismiss: 'Ignorer',
    },
    de: {
      promptH1: 'Was überfordert dich heute?',
      subtext: 'Schreib es auf. Ich zerlege es in kleine, machbare Schritte — direkt hier auf deinem Handy.',
      placeholder: 'z. B. „Die Geburtstagsfeier meiner Schwester nächstes Wochenende planen“',
      submitCta: 'In Schritte zerlegen',
      privacyFootnote: 'Läuft komplett auf deinem Handy. Nichts wird irgendwohin gesendet.',
      loadingTitle: 'Ich denke auf deinem Handy darüber nach…',
      loadingOffline: 'Funktioniert im Flugmodus. Deine Worte verlassen dieses Handy nie.',
      preparingTitle: 'Alles wird vorbereitet — komplett auf deinem Handy.',
      taskChipLabel: 'Deine Aufgabe:',
      stopButton: 'Stopp',
      allComplete: 'Gut gemacht. Du hast es geschafft — Schritt für Schritt.',
      emptyResult: 'Das konnte ich gerade nicht zerlegen. Versuch es noch mal — oder formuliere es etwas um.',
      error: 'Hier hat etwas gehakt. Dein Text ist sicher — versuchen wir es noch mal.',
      retryButton: 'Noch mal versuchen',
      editButton: 'Bearbeiten',
      startOverButton: 'Von vorn beginnen',
      breakDownStepCta: 'In kleinere Schritte zerlegen',
      breakingDownStep: 'Wird auf deinem Handy zerlegt…',
      breakdownEmpty: 'Kleiner geht dieser Schritt kaum noch.',
      breakdownError: 'Konnte ihn nicht zerlegen — versuch es noch mal.',
      recoveredDraftLabel: 'Die App wurde geschlossen, bevor deine letzte Aufgabe fertig war:',
      recoveredDraftResume: 'Fortsetzen',
      recoveredDraftDismiss: 'Verwerfen',
    },
    it: {
      promptH1: 'Cosa ti sta sopraffacendo oggi?',
      subtext: 'Scrivilo. Lo dividerò in piccoli passi fattibili — proprio qui, sul tuo telefono.',
      placeholder: 'es. «Organizzare il compleanno di mia sorella il prossimo weekend»',
      submitCta: 'Dividi in passi',
      privacyFootnote: 'Funziona interamente sul tuo telefono. Nulla viene inviato da nessuna parte.',
      loadingTitle: 'Ci sto pensando sul tuo telefono…',
      loadingOffline: 'Funziona in modalità aereo. Le tue parole non lasciano mai questo telefono.',
      preparingTitle: 'Sto preparando tutto, interamente sul tuo telefono.',
      taskChipLabel: 'La tua richiesta:',
      stopButton: 'Ferma',
      allComplete: 'Ben fatto. Ce l’hai fatta, un passo alla volta.',
      emptyResult: 'Non sono riuscito a dividerlo questa volta. Riprova — o cambia un po’ le parole.',
      error: 'Qualcosa è andato storto qui. Il tuo testo è al sicuro — riproviamo.',
      retryButton: 'Riprova',
      editButton: 'Modifica',
      startOverButton: 'Ricomincia',
      breakDownStepCta: 'Dividi in passi più piccoli',
      breakingDownStep: 'Lo sto dividendo sul tuo telefono…',
      breakdownEmpty: 'Questo passo è già piccolo così.',
      breakdownError: 'Non sono riuscito a dividerlo — riprova.',
      recoveredDraftLabel: 'L’app si è chiusa prima di finire la tua ultima attività:',
      recoveredDraftResume: 'Riprendi',
      recoveredDraftDismiss: 'Scarta',
    },
    pt: {
      promptH1: 'O que está te sobrecarregando hoje?',
      subtext: 'Escreva aqui. Vou dividir em passos pequenos e possíveis — aqui mesmo, no seu telefone.',
      placeholder: 'ex. "Planejar o aniversário da minha irmã no próximo fim de semana"',
      submitCta: 'Dividir em passos',
      privacyFootnote: 'Funciona totalmente no seu telefone. Nada é enviado a lugar nenhum.',
      loadingTitle: 'Pensando nisso no seu telefone…',
      loadingOffline: 'Funciona em modo avião. Suas palavras nunca saem deste telefone.',
      preparingTitle: 'Preparando tudo, totalmente no seu telefone.',
      taskChipLabel: 'Seu pedido:',
      stopButton: 'Parar',
      allComplete: 'Muito bem. Você conseguiu, um passo de cada vez.',
      emptyResult: 'Não consegui dividir agora. Tente de novo — ou mude um pouco as palavras.',
      error: 'Algo travou por aqui. Seu texto está seguro — vamos tentar de novo.',
      retryButton: 'Tentar de novo',
      editButton: 'Editar',
      startOverButton: 'Começar de novo',
      breakDownStepCta: 'Dividir em passos menores',
      breakingDownStep: 'Dividindo no seu telefone…',
      breakdownEmpty: 'Esse passo já é pequeno o suficiente.',
      breakdownError: 'Não consegui dividir — tente de novo.',
      recoveredDraftLabel: 'O app fechou antes de terminar sua última tarefa:',
      recoveredDraftResume: 'Retomar',
      recoveredDraftDismiss: 'Descartar',
    },
    hi: {
      promptH1: 'आज आपको क्या भारी लग रहा है?',
      subtext: 'लिख दीजिए। मैं इसे छोटे, आसान क़दमों में बाँट दूँगा — यहीं, आपके फ़ोन पर।',
      placeholder: 'जैसे "अगले हफ़्ते बहन का जन्मदिन प्लान करना"',
      submitCta: 'क़दमों में बाँटें',
      privacyFootnote: 'पूरी तरह आपके फ़ोन पर चलता है। कुछ भी कहीं नहीं भेजा जाता।',
      loadingTitle: 'आपके फ़ोन पर ही इस पर सोच रहा हूँ…',
      loadingOffline: 'एयरप्लेन मोड में भी चलता है। आपके शब्द इस फ़ोन से बाहर नहीं जाते।',
      preparingTitle: 'तैयारी हो रही है — पूरी तरह आपके फ़ोन पर।',
      taskChipLabel: 'आपने पूछा:',
      stopButton: 'रोकें',
      allComplete: 'बहुत बढ़िया। आपने इसे संभाल लिया — एक-एक क़दम करके।',
      emptyResult: 'इसे अभी बाँट नहीं पाया। फिर से कोशिश करें — या शब्द थोड़े बदलकर देखें।',
      error: 'इस तरफ़ कुछ अटक गया। आपका लिखा सुरक्षित है — चलिए, फिर से कोशिश करते हैं।',
      retryButton: 'फिर कोशिश करें',
      editButton: 'बदलें',
      startOverButton: 'नए सिरे से',
      breakDownStepCta: 'इसे और छोटे क़दमों में बाँटें',
      breakingDownStep: 'आपके फ़ोन पर ही बाँट रहा हूँ…',
      breakdownEmpty: 'यह क़दम पहले से ही काफ़ी छोटा है।',
      breakdownError: 'इसे बाँट नहीं पाया — फिर कोशिश करें।',
      recoveredDraftLabel: 'पिछला काम पूरा होने से पहले ऐप बंद हो गया था:',
      recoveredDraftResume: 'जारी रखें',
      recoveredDraftDismiss: 'हटा दें',
    },
  },
);
